package main

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// embeddedPlatformCollections is the generated declared-schema set for the
// `_platform.*` collections, synced from `contracts/`.
//
// Their shapes live in the actuator's synthetic manifest, which is Rust, so
// they appear in no plugin.json — and three first-party plugins consume
// `_platform.key_names`. Without this the emitter could type two thirds of
// the fleet's declared reads and would silently skip the rest.
//
//go:embed specs/platform-collections.json
var embeddedPlatformCollections []byte

// providerFields maps a collection name to the fields its introducer
// declares, keyed by field name.
type providerFields map[string]map[string]ActionFieldSchema

// resolveProviders builds the collection -> declared-fields index that a
// consumer's field claim is typed against.
//
// From DISK, which is decision (g): this tool already resolves manifests by
// walking sibling directories for plugin.json, so typing a consumer's claim
// needs no new resolution path for the workspace or for install-then-generate
// — and the bundled first-party collections are what a third party consumes
// in nearly every case.
func resolveProviders(root string) providerFields {
	out := providerFields{}

	var platform struct {
		Collections map[string]struct {
			Fields []ActionFieldSchema `json:"fields"`
		} `json:"collections"`
	}
	if err := json.Unmarshal(embeddedPlatformCollections, &platform); err == nil {
		for name, schema := range platform.Collections {
			out[name] = indexFields(schema.Fields)
		}
	}

	for _, dir := range enumeratePluginDirs(root) {
		raw, err := os.ReadFile(filepath.Join(dir, "plugin.json"))
		if err != nil {
			continue
		}
		var m struct {
			Provides struct {
				Collections map[string]struct {
					Fields []ActionFieldSchema `json:"fields"`
				} `json:"collections"`
			} `json:"provides"`
		}
		if json.Unmarshal(raw, &m) != nil {
			continue
		}
		for name, schema := range m.Provides.Collections {
			// A family reservation is not a collection and declares no shape.
			if strings.HasSuffix(name, "*") {
				continue
			}
			out[name] = indexFields(schema.Fields)
		}
	}
	return out
}

func indexFields(fields []ActionFieldSchema) map[string]ActionFieldSchema {
	m := make(map[string]ActionFieldSchema, len(fields))
	for _, f := range fields {
		m[f.Key] = f
	}
	return m
}

// collectionRecordName turns a collection name into a Go type name.
// `_platform.key_names` becomes `PlatformKeyNamesRecord`.
func collectionRecordName(collection string) string {
	return GoIdentifier(collection) + "Record"
}

// consumedShape is one collection this plugin reads, with the provider's
// schema for exactly the fields it claimed.
type consumedShape struct {
	Collection string
	Fields     []ActionFieldSchema
}

// resolveConsumedShapes pairs each shaped consumption entry with the
// provider's declaration of the fields it named.
//
// A claimed field the provider does not declare is DROPPED here rather than
// guessed at. The platform already reports that mismatch as a load-time
// warning naming both sides (`shape_issues`); inventing a type for a field
// nobody publishes would turn a diagnostic into a silently wrong struct.
func resolveConsumedShapes(manifest *PluginManifest, providers providerFields) []consumedShape {
	var out []consumedShape
	for _, c := range manifest.Consumes.Collections {
		if len(c.Fields) == 0 {
			continue
		}
		known, ok := providers[c.Name]
		if !ok {
			continue
		}
		var fields []ActionFieldSchema
		for _, want := range c.Fields {
			if f, ok := known[want]; ok {
				fields = append(fields, f)
			}
		}
		if len(fields) > 0 {
			out = append(out, consumedShape{c.Name, fields})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Collection < out[j].Collection })
	return out
}

// RenderGoCollections produces collections_gen.go: one struct per consumed
// collection whose manifest entry names the fields it reads.
//
// The consumer declares WHICH fields; the provider's schema supplies their
// TYPES. That split is what makes the generated type trustworthy — a consumer
// never states a type, so it cannot state a wrong one, and the provider stays
// the single source of truth. It also means a provider's rename breaks the
// consumer at COMPILE time on the next generate, rather than zero-filling a
// hand-written struct at runtime with no error anywhere.
//
// Returns "" when the plugin declares no shaped consumption, so a plugin that
// reads nothing gets no file.
func RenderGoCollections(manifest *PluginManifest, providers providerFields) string {
	shapes := resolveConsumedShapes(manifest, providers)
	if len(shapes) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("// AUTO-GENERATED by branchkit-gen — do not edit.\n")
	b.WriteString("// Source: plugin.json `consumes.collections` field claims, typed from\n")
	b.WriteString("// each provider's declared schema. Run: just gen-plugins\n\n")
	b.WriteString("package main\n\n")

	// Opaque field types render as json.RawMessage and need the import. The
	// action emitter pre-scans for the same reason; omitting it here emitted a
	// file that did not compile, and only for plugins reading an object- or
	// json-typed field.
	needsJSON := false
	for _, sh := range shapes {
		for i := range sh.Fields {
			if sh.Fields[i].EffectiveFieldType().NeedsJSONImport() {
				needsJSON = true
			}
		}
	}
	if needsJSON {
		b.WriteString("import \"encoding/json\"\n\n")
	}

	for _, s := range shapes {
		name := collectionRecordName(s.Collection)
		fmt.Fprintf(&b, "// %s is the shape this plugin declared it reads from the\n", name)
		fmt.Fprintf(&b, "// %q collection. Unmarshal a CollectionRecord's Payload into it.\n", s.Collection)
		fmt.Fprintf(&b, "type %s struct {\n", name)
		for i := range s.Fields {
			f := s.Fields[i]
			fmt.Fprintf(&b, "\t%s %s `json:%q`\n", GoIdentifier(f.Key), goFieldType(name, &f), f.Key)
		}
		b.WriteString("}\n\n")
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return b.String()
	}
	return string(formatted)
}

// RenderTSCollections produces collections_gen.ts. Same contract as the Go
// emitter: the consumer names the fields, the provider types them.
//
// Optional fields carry `?` rather than a wider type, so a field the provider
// did not mark required is one the consumer has to handle being absent —
// which is the whole reason to generate this instead of hand-writing it.
func RenderTSCollections(manifest *PluginManifest, providers providerFields) string {
	shapes := resolveConsumedShapes(manifest, providers)
	if len(shapes) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("// AUTO-GENERATED by branchkit-gen — do not edit.\n")
	b.WriteString("// Source: plugin.json `consumes.collections` field claims, typed from\n")
	b.WriteString("// each provider's declared schema. Run: just gen-plugins\n\n")
	for _, s := range shapes {
		name := collectionRecordName(s.Collection)
		fmt.Fprintf(&b, "/** Shape this plugin declared it reads from `%s`. */\n", s.Collection)
		fmt.Fprintf(&b, "export interface %s {\n", name)
		for i := range s.Fields {
			f := s.Fields[i]
			opt := "?"
			if f.Required {
				opt = ""
			}
			fmt.Fprintf(&b, "  %s%s: %s;\n", f.Key, opt, tsFieldType(name, &f))
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

// RenderPyCollections produces collections_gen.py.
//
// TypedDict with total=False, because a provider that did not mark a field
// required has not promised it will be there.
func RenderPyCollections(manifest *PluginManifest, providers providerFields) string {
	shapes := resolveConsumedShapes(manifest, providers)
	if len(shapes) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("# AUTO-GENERATED by branchkit-gen — do not edit.\n")
	b.WriteString("# Source: plugin.json `consumes.collections` field claims, typed from\n")
	b.WriteString("# each provider's declared schema. Run: just gen-plugins\n\n")
	b.WriteString("from typing import Any, TypedDict\n\n")
	for _, s := range shapes {
		name := collectionRecordName(s.Collection)
		fmt.Fprintf(&b, "class %s(TypedDict, total=False):\n", name)
		fmt.Fprintf(&b, "    \"\"\"Shape this plugin declared it reads from `%s`.\"\"\"\n\n", s.Collection)
		for i := range s.Fields {
			f := s.Fields[i]
			fmt.Fprintf(&b, "    %s: %s\n", f.Key, pyFieldType(name, &f))
		}
		b.WriteString("\n\n")
	}
	return b.String()
}
