package main

import (
	"fmt"
	"sort"
	"strings"
)

// RenderGo produces the contents of actions_gen.go from a plugin manifest.
func RenderGo(manifest *PluginManifest) string {
	names := sortedActionNames(manifest.ActionTypes)

	// Pre-scan: do any fields need encoding/json?
	needsJSON := false
	for _, name := range names {
		schema := manifest.ActionTypes[name]
		for _, f := range schema.Fields {
			if f.EffectiveFieldType().NeedsJSONImport() {
				needsJSON = true
				break
			}
		}
		if needsJSON {
			break
		}
	}

	var b strings.Builder
	b.WriteString("// AUTO-GENERATED by emit-sdk — do not edit.\n")
	b.WriteString("// Source: plugin.json `action_types`. Run: just gen-plugins\n")
	b.WriteString("\n")
	b.WriteString("package main\n")
	b.WriteString("\n")

	if needsJSON {
		b.WriteString("import \"encoding/json\"\n\n")
		b.WriteString("// Ensure json import is used even when no struct field references it.\n")
		b.WriteString("var _ json.RawMessage\n\n")
	}

	prefix := ""
	if manifest.ActionPrefix != nil {
		prefix = *manifest.ActionPrefix
	}

	for _, name := range names {
		schema := manifest.ActionTypes[name]
		structName := GoIdentifier(name)
		fullAction := name
		if prefix != "" {
			fullAction = prefix + "." + name
		}

		// Enum type declarations precede the struct.
		for _, field := range schema.Fields {
			if field.EffectiveFieldType() == FieldTypeEnum {
				enumName := enumTypeName(structName, field.Key)
				renderGoEnum(&b, enumName, field.EnumValues)
				b.WriteString("\n")
			}
		}

		renderGoStruct(&b, structName, fullAction, &schema)
		b.WriteString("\n")
	}

	return b.String()
}

func renderGoEnum(b *strings.Builder, typeName string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(b, "// %s is a generated enum type.\n", typeName)
	fmt.Fprintf(b, "type %s string\n\n", typeName)
	b.WriteString("const (\n")
	for _, v := range values {
		constSuffix := GoIdentifier(v)
		fmt.Fprintf(b, "\t%s%s %s = %q\n", typeName, constSuffix, typeName, v)
	}
	b.WriteString(")\n")
}

func renderGoStruct(b *strings.Builder, structName, fullAction string, schema *ActionTypeSchema) {
	label := fullAction
	if schema.Label != "" {
		label = fmt.Sprintf("%s (%s)", fullAction, schema.Label)
	}
	fmt.Fprintf(b, "// %sParams is the params shape for action %q.\n", structName, label)
	fmt.Fprintf(b, "type %sParams struct {\n", structName)
	for _, field := range schema.Fields {
		goTy := goFieldType(structName, &field)
		goName := GoIdentifier(field.Key)
		jsonTag := field.Key
		if !field.Required {
			jsonTag += ",omitempty"
		}
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", goName, goTy, jsonTag)
	}
	b.WriteString("}\n")
}

func goFieldType(structName string, field *ActionFieldSchema) string {
	ft := field.EffectiveFieldType()
	switch ft {
	case FieldTypeString:
		if field.Required {
			return "string"
		}
		return "*string"
	case FieldTypeInt:
		if field.Required {
			return "int"
		}
		return "*int"
	case FieldTypeNumber:
		if field.Required {
			return "float64"
		}
		return "*float64"
	case FieldTypeBoolean:
		if field.Required {
			return "bool"
		}
		return "*bool"
	case FieldTypeStringArray:
		return "[]string"
	case FieldTypeEnum:
		name := enumTypeName(structName, field.Key)
		if field.Required {
			return name
		}
		return "*" + name
	case FieldTypeObject, FieldTypeJson:
		return "json.RawMessage"
	default:
		// Unknown field type — fall through to dynamic.
		return "json.RawMessage"
	}
}

func enumTypeName(structName, fieldKey string) string {
	return structName + GoIdentifier(fieldKey)
}

func sortedActionNames(m map[string]ActionTypeSchema) []string {
	names := make([]string, 0, len(m))
	for k := range m {
		names = append(names, k)
	}
	sort.Strings(names)
	return names
}
