package main

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// RenderGo produces the contents of actions_gen.go from a plugin manifest.
// The output is gofmt-formatted: hand-aligned emission drifted from gofmt's
// struct-tag alignment, leaving every generated file a permanent
// `just fmt-check` failure that check-gen then pinned in place.
func RenderGo(manifest *PluginManifest) string {
	names := sortedActionNames(manifest.ActionTypes)

	// Pre-scan: do any fields need encoding/json?
	needsJSON := false
	for _, name := range names {
		schema := manifest.ActionTypes[name]
		for _, f := range schema.Fields {
			if f.EffectiveFieldType().NeedsJSONImport() {
				needsJSON = true
				break
			}
		}
		if needsJSON {
			break
		}
	}

	var b strings.Builder
	b.WriteString("// AUTO-GENERATED by emit-sdk — do not edit.\n")
	b.WriteString("// Source: plugin.json `action_types`. Run: just gen-plugins\n")
	b.WriteString("\n")
	b.WriteString("package main\n")
	b.WriteString("\n")

	// The SDK import backs the generated Handle<Action> registrars below.
	// Only needed when there is at least one action to register.
	needsSDK := len(names) > 0
	switch {
	case needsJSON && needsSDK:
		b.WriteString("import (\n\t\"encoding/json\"\n\n\tshared \"github.com/branchkit/plugin-sdk-go\"\n)\n\n")
	case needsJSON:
		b.WriteString("import \"encoding/json\"\n\n")
	case needsSDK:
		b.WriteString("import shared \"github.com/branchkit/plugin-sdk-go\"\n\n")
	}
	if needsJSON {
		b.WriteString("// Ensure json import is used even when no struct field references it.\n")
		b.WriteString("var _ json.RawMessage\n\n")
	}

	prefix := ""
	if manifest.ActionPrefix != nil {
		prefix = *manifest.ActionPrefix
	}

	for _, name := range names {
		schema := manifest.ActionTypes[name]
		structName := GoIdentifier(name)
		fullAction := name
		if prefix != "" {
			fullAction = prefix + "." + name
		}

		// Enum type declarations precede the struct.
		for _, field := range schema.Fields {
			if field.EffectiveFieldType() == FieldTypeEnum {
				enumName := enumTypeName(structName, field.Key)
				renderGoEnum(&b, enumName, field.EnumValues)
				b.WriteString("\n")
			}
		}

		renderGoStruct(&b, structName, fullAction, &schema)
		b.WriteString("\n")
		renderGoActionHandler(&b, structName, fullAction, &schema)
		b.WriteString("\n")
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		// The emitter produced invalid Go — a bug here, never a caller
		// condition. Panic with the raw source so the test that trips this
		// shows what was emitted.
		panic(fmt.Sprintf("RenderGo emitted unparseable Go: %v\n---\n%s", err, b.String()))
	}
	return string(formatted)
}

func renderGoEnum(b *strings.Builder, typeName string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(b, "// %s is a generated enum type.\n", typeName)
	fmt.Fprintf(b, "type %s string\n\n", typeName)
	b.WriteString("const (\n")
	for _, v := range values {
		constSuffix := GoIdentifier(v)
		fmt.Fprintf(b, "\t%s%s %s = %q\n", typeName, constSuffix, typeName, v)
	}
	b.WriteString(")\n")
}

func renderGoStruct(b *strings.Builder, structName, fullAction string, schema *ActionTypeSchema) {
	label := fullAction
	if schema.Label != "" {
		label = fmt.Sprintf("%s (%s)", fullAction, schema.Label)
	}
	fmt.Fprintf(b, "// %sParams is the params shape for action %q.\n", structName, label)
	fmt.Fprintf(b, "type %sParams struct {\n", structName)
	for _, field := range schema.Fields {
		goTy := goFieldType(structName, &field)
		goName := GoIdentifier(field.Key)
		jsonTag := field.Key
		if !field.Required {
			jsonTag += ",omitempty"
		}
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", goName, goTy, jsonTag)
	}
	b.WriteString("}\n")
}

// renderGoActionHandler emits a typed registrar for one action.
//
// The SDK already had `HandleActionTyped[T]`, the generated params structs
// already existed, and the demand was proven by `HandleTyped`'s 100+ callers —
// yet across seven plugins there were 49 untyped `HandleAction` registrations
// and zero typed ones. The 2026-08-11 platform gap audit read that as an
// adoption failure with a specific shape: the untyped escape hatch is always
// shorter at the call site, so it always wins.
//
//	// before — action string and params type are both hand-written, and
//	// nothing checks either against plugin.json
//	plugin.HandleAction("windows.snap", func(req *shared.OnActionRequest) (any, error) {
//	    var p SnapParams
//	    if err := req.UnmarshalParams(&p); err != nil { return nil, err }
//	    ...
//	})
//
//	// after
//	HandleSnap(plugin, func(p SnapParams, req *shared.OnActionRequest) (any, error) { ... })
//
// Generating the registrar inverts the gradient rather than exhorting anyone:
// the typed path is now the shortest one, and the action string and params
// type both come from the manifest, so neither can drift from it.
func renderGoActionHandler(b *strings.Builder, structName, fullAction string, schema *ActionTypeSchema) {
	label := fullAction
	if schema.Label != "" {
		label = fmt.Sprintf("%s (%s)", fullAction, schema.Label)
	}
	fmt.Fprintf(b, "// Handle%s registers a typed handler for action %q.\n", structName, label)

	// An action with no declared fields takes no params argument. Threading an
	// always-empty struct through would make the generated registrar LONGER
	// than the untyped HandleAction it replaces — reintroducing the very
	// gradient this exists to invert, for 29 of the 67 first-party actions.
	// It also means those handlers keep the exact signature they already have,
	// so migrating one is a single line at the registration site.
	if len(schema.Fields) == 0 {
		fmt.Fprintf(
			b,
			"func Handle%s(p *shared.Plugin, fn shared.ActionHandlerFunc) {\n",
			structName,
		)
		fmt.Fprintf(b, "\tp.HandleAction(%q, fn)\n", fullAction)
		b.WriteString("}\n")
		return
	}

	fmt.Fprintf(
		b,
		"func Handle%s(p *shared.Plugin, fn func(%sParams, *shared.OnActionRequest) (any, error)) {\n",
		structName, structName,
	)
	fmt.Fprintf(b, "\tshared.HandleActionTyped(p, %q, fn)\n", fullAction)
	b.WriteString("}\n")
}

func goFieldType(structName string, field *ActionFieldSchema) string {
	ft := field.EffectiveFieldType()
	switch ft {
	case FieldTypeString:
		if field.Required {
			return "string"
		}
		return "*string"
	case FieldTypeInt:
		if field.Required {
			return "int"
		}
		return "*int"
	case FieldTypeNumber:
		if field.Required {
			return "float64"
		}
		return "*float64"
	case FieldTypeBoolean:
		if field.Required {
			return "bool"
		}
		return "*bool"
	case FieldTypeStringArray:
		return "[]string"
	case FieldTypeEnum:
		name := enumTypeName(structName, field.Key)
		if field.Required {
			return name
		}
		return "*" + name
	case FieldTypeObject, FieldTypeJson:
		return "json.RawMessage"
	default:
		// Unknown field type — fall through to dynamic.
		return "json.RawMessage"
	}
}

func enumTypeName(structName, fieldKey string) string {
	return structName + GoIdentifier(fieldKey)
}

func sortedActionNames(m map[string]ActionTypeSchema) []string {
	names := make([]string, 0, len(m))
	for k := range m {
		names = append(names, k)
	}
	sort.Strings(names)
	return names
}
