package main

import (
	"path/filepath"
	"strings"
)

// Where each language's generated files go, read from the plugin's layout on
// disk. The rules match what `branchkit-cli dev init` scaffolds and what
// `branchkit-cli dev build` builds, so a freshly scaffolded plugin in any of
// the three languages regenerates with no setup:
//
//	Go          src/go.mod                               -> src/
//	TypeScript  package.json (root or src/) + an entry   -> beside the entry
//	            module (src/index.ts, index.ts, src/main.ts)
//	Python      `run` starts with python, or a main.py   -> beside main.py
//	            (src/ or the plugin root)
//
// Older layouts keep working: src/package.json alone still means TypeScript
// in src/, and src/pyproject.toml alone still means Python in src/.

// goOutDir returns src/ when the plugin is a Go module there.
func goOutDir(dir string) (string, bool) {
	src := filepath.Join(dir, "src")
	if fileExists(filepath.Join(src, "go.mod")) {
		return src, true
	}
	return "", false
}

// tsEntries are the entry modules `branchkit-cli dev build` looks for, in
// its order.
var tsEntries = []string{"src/index.ts", "index.ts", "src/main.ts"}

// tsOutDir returns the directory holding the plugin's TypeScript entry
// module, so `import type { … } from "./actions_gen.js"` resolves from it.
func tsOutDir(dir string) (string, bool) {
	src := filepath.Join(dir, "src")
	srcPkg := fileExists(filepath.Join(src, "package.json"))
	rootPkg := fileExists(filepath.Join(dir, "package.json"))
	if !srcPkg && !rootPkg {
		return "", false
	}
	for _, rel := range tsEntries {
		if fileExists(filepath.Join(dir, rel)) {
			return filepath.Dir(filepath.Join(dir, rel)), true
		}
	}
	// A package.json with no entry module: only the src/-rooted layout is
	// unambiguous. A root package.json alone can belong to tooling beside a
	// plugin written in another language.
	if srcPkg {
		return src, true
	}
	return "", false
}

// pyOutDir returns the directory holding the plugin's Python entrypoint.
func pyOutDir(dir string, manifest *PluginManifest) (string, bool) {
	src := filepath.Join(dir, "src")
	if fileExists(filepath.Join(src, "main.py")) {
		return src, true
	}
	if fileExists(filepath.Join(dir, "main.py")) || strings.HasPrefix(manifest.Run, "python") {
		return dir, true
	}
	if fileExists(filepath.Join(src, "pyproject.toml")) {
		return src, true
	}
	return "", false
}

// The header every generated file starts with. The Go form matches the
// convention tools use to recognise generated code (`^// Code generated .*
// DO NOT EDIT\.$`); the TypeScript and Python forms say the same thing.
//
// The regenerate line names the command a plugin author runs. It never names
// a build recipe of any particular repository: the same header lands in
// first-party and third-party plugins alike.

func actionsHeader(comment string) string {
	return comment + " Code generated by branchkit-gen from plugin.json `action_types`. DO NOT EDIT.\n" +
		comment + " Regenerate from the plugin directory: branchkit-gen --plugin .\n"
}

// Collection shapes are typed from each provider's declared schema: the
// platform's own collections, or a provider plugin in a directory beside
// this one. Regenerating from the parent directory is what lets
// branchkit-gen find those providers.
func collectionsHeader(comment string) string {
	return comment + " Code generated by branchkit-gen from plugin.json `consumes.collections`. DO NOT EDIT.\n" +
		comment + " Field types come from each provider's declared schema: the platform's\n" +
		comment + " collections, or a provider plugin in a directory beside this one.\n" +
		comment + " Regenerate from the parent directory: branchkit-gen --plugin <this plugin's directory>\n"
}
