package main

import (
	"fmt"
	"strings"
)

// RenderPy produces the contents of actions_gen.py from a plugin manifest —
// the Python twin of RenderGo / RenderTS.
//
// TypedDicts use the FUNCTIONAL form (`Foo = TypedDict("Foo", {...})`)
// because field keys are wire strings and the class form cannot declare a
// key that is a Python keyword. Each action also gets a `handle_<name>`
// registrar, for the same reason Go got one: the action string comes from
// the manifest, so a handler cannot drift from what the plugin declares,
// and the typed path stays the shortest one.
func RenderPy(manifest *PluginManifest) string {
	names := sortedActionNames(manifest.ActionTypes)

	// Pre-scan for the typing names actually used, the way RenderGo scans for
	// encoding/json: an unused import in generated code is lint noise every
	// consumer inherits and none of them can fix.
	needs := map[string]bool{"TypedDict": len(names) > 0}
	for _, name := range names {
		for _, f := range manifest.ActionTypes[name].Fields {
			if !f.Required {
				needs["NotRequired"] = true
			}
			switch f.EffectiveFieldType() {
			case FieldTypeEnum:
				needs["Literal"] = true
			case FieldTypeObject, FieldTypeJson:
				needs["Any"] = true
			}
		}
	}
	var imports []string
	for _, n := range []string{"Any", "Literal", "NotRequired", "TypedDict"} {
		if needs[n] {
			imports = append(imports, n)
		}
	}

	var b strings.Builder
	b.WriteString("# AUTO-GENERATED by emit-sdk — do not edit.\n")
	b.WriteString("# Source: plugin.json `action_types`. Run: just gen-plugins\n")
	if len(imports) > 0 {
		b.WriteString("\n")
		fmt.Fprintf(&b, "from typing import %s\n", strings.Join(imports, ", "))
	}

	prefix := ""
	if manifest.ActionPrefix != nil {
		prefix = *manifest.ActionPrefix
	}

	for _, name := range names {
		schema := manifest.ActionTypes[name]
		typeName := GoIdentifier(name)
		fullAction := name
		if prefix != "" {
			fullAction = prefix + "." + name
		}

		b.WriteString("\n")
		for _, field := range schema.Fields {
			if field.EffectiveFieldType() == FieldTypeEnum {
				renderPyEnum(&b, enumTypeName(typeName, field.Key), field.EnumValues)
			}
		}

		renderPyTypedDict(&b, typeName, fullAction, &schema)
		b.WriteString("\n")
		renderPyActionRegistrar(&b, typeName, name, fullAction, &schema)
	}

	return b.String()
}

func renderPyEnum(b *strings.Builder, typeName string, values []string) {
	if len(values) == 0 {
		return
	}
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = fmt.Sprintf("%q", v)
	}
	fmt.Fprintf(b, "%s = Literal[%s]\n", typeName, strings.Join(parts, ", "))
	b.WriteString("\n")
}

func renderPyTypedDict(b *strings.Builder, typeName, fullAction string, schema *ActionTypeSchema) {
	label := fullAction
	if schema.Label != "" {
		label = fmt.Sprintf("%s (%s)", fullAction, schema.Label)
	}
	fmt.Fprintf(b, "# Params shape for action %q.\n", label)
	fmt.Fprintf(b, "%sParams = TypedDict(%q, {\n", typeName, typeName+"Params")
	for _, field := range schema.Fields {
		pyTy := pyFieldType(typeName, &field)
		if !field.Required {
			pyTy = "NotRequired[" + pyTy + "]"
		}
		fmt.Fprintf(b, "    %q: %s,\n", field.Key, pyTy)
	}
	b.WriteString("})\n")
}

func renderPyActionRegistrar(b *strings.Builder, typeName, name, fullAction string, schema *ActionTypeSchema) {
	label := fullAction
	if schema.Label != "" {
		label = fmt.Sprintf("%s (%s)", fullAction, schema.Label)
	}
	fnName := "handle_" + PyIdentifier(name)
	// `fn=None` returns a decorator, so both forms work off one definition:
	//   handle_greet(plugin, fn)     — direct
	//   @handle_greet(plugin)        — decorator
	// The SDK's handle_action already has that shape; this just forwards it.
	fmt.Fprintf(b, "def %s(plugin, fn=None):\n", fnName)
	if len(schema.Fields) == 0 {
		fmt.Fprintf(b, "    \"\"\"Register a handler for action %q.\"\"\"\n", label)
	} else {
		fmt.Fprintf(
			b,
			"    \"\"\"Register a handler for action %q — `fn(req)` where\n    req[\"params\"] is %sParams-shaped.\"\"\"\n",
			label, typeName,
		)
	}
	fmt.Fprintf(b, "    return plugin.handle_action(%q, fn)\n", fullAction)
}

// PyIdentifier converts a dotted/kebab key to a snake_case Python
// identifier: "snap-to" → "snap_to", "media.play" → "media_play".
func PyIdentifier(s string) string {
	return strings.Join(splitIdentifierLower(s), "_")
}

func splitIdentifierLower(s string) []string {
	parts := splitIdentifier(s)
	out := make([]string, len(parts))
	for i, p := range parts {
		out[i] = strings.ToLower(p)
	}
	return out
}

func pyFieldType(typeName string, field *ActionFieldSchema) string {
	switch field.EffectiveFieldType() {
	case FieldTypeString:
		return "str"
	case FieldTypeInt:
		return "int"
	case FieldTypeNumber:
		return "float"
	case FieldTypeBoolean:
		return "bool"
	case FieldTypeStringArray:
		return "list[str]"
	case FieldTypeEnum:
		return enumTypeName(typeName, field.Key)
	case FieldTypeObject, FieldTypeJson:
		return "Any"
	default:
		return "Any"
	}
}
