package main

import (
	"fmt"
	"strings"
)

// RenderTS produces the contents of actions_gen.ts from a plugin manifest.
func RenderTS(manifest *PluginManifest) string {
	names := sortedActionNames(manifest.ActionTypes)

	var b strings.Builder
	b.WriteString("// AUTO-GENERATED by emit-sdk — do not edit.\n")
	b.WriteString("// Source: plugin.json `action_types`. Run: just gen-plugins\n")
	b.WriteString("\n")

	prefix := ""
	if manifest.ActionPrefix != nil {
		prefix = *manifest.ActionPrefix
	}

	for _, name := range names {
		schema := manifest.ActionTypes[name]
		ifaceName := GoIdentifier(name)
		fullAction := name
		if prefix != "" {
			fullAction = prefix + "." + name
		}

		for _, field := range schema.Fields {
			if field.EffectiveFieldType() == FieldTypeEnum {
				enumName := enumTypeName(ifaceName, field.Key)
				renderTSEnum(&b, enumName, field.EnumValues)
				b.WriteString("\n")
			}
		}

		renderTSInterface(&b, ifaceName, fullAction, &schema)
		b.WriteString("\n")
	}

	return b.String()
}

func renderTSEnum(b *strings.Builder, typeName string, values []string) {
	if len(values) == 0 {
		return
	}
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = fmt.Sprintf("%q", v)
	}
	fmt.Fprintf(b, "export type %s = %s;\n", typeName, strings.Join(parts, " | "))
}

func renderTSInterface(b *strings.Builder, ifaceName, fullAction string, schema *ActionTypeSchema) {
	label := fullAction
	if schema.Label != "" {
		label = fmt.Sprintf("%s (%s)", fullAction, schema.Label)
	}
	fmt.Fprintf(b, "/** Params shape for action %q. */\n", label)
	fmt.Fprintf(b, "export interface %sParams {\n", ifaceName)
	for _, field := range schema.Fields {
		tsTy := tsFieldType(ifaceName, &field)
		optional := ""
		if !field.Required {
			optional = "?"
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", field.Key, optional, tsTy)
	}
	b.WriteString("}\n")
}

func tsFieldType(ifaceName string, field *ActionFieldSchema) string {
	ft := field.EffectiveFieldType()
	switch ft {
	case FieldTypeString:
		return "string"
	case FieldTypeInt, FieldTypeNumber:
		return "number"
	case FieldTypeBoolean:
		return "boolean"
	case FieldTypeStringArray:
		return "string[]"
	case FieldTypeEnum:
		return enumTypeName(ifaceName, field.Key)
	case FieldTypeObject, FieldTypeJson:
		return "unknown"
	default:
		return "unknown"
	}
}
